In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
exl_file = pd.ExcelFile("../dataset/hr_dataset.xlsx")

In [7]:
exl_file.sheet_names

['Employees', 'Departments', 'Locations', 'Jobs', 'Attendance', 'Attrition']

Load the data

In [8]:
employees = pd.read_excel("../dataset/hr_dataset.xlsx",sheet_name="Employees")
departments = pd.read_excel("../dataset/hr_dataset.xlsx",sheet_name="Departments")
locations = pd.read_excel("../dataset/hr_dataset.xlsx",sheet_name="Locations")
jobs = pd.read_excel("../dataset/hr_dataset.xlsx",sheet_name="Jobs")
attendance = pd.read_excel("../dataset/hr_dataset.xlsx",sheet_name="Attendance")
attrition = pd.read_excel("../dataset/hr_dataset.xlsx",sheet_name="Attrition")

In [9]:
employees.head()

,EmployeeID,EmpCode,DeptID,LocationID,JobID,HireDate,Age,Gender,EmploymentStatus,Salary,PerformanceRating,TrainingHours,AbsenteeismDays,OvertimeHours,EngagementScore,SatisfactionScore,YearsSincePromotion,Bonus,ManagerID
0,1,E0001,6,1,1,2021-01-31,36,Male,Active,644704,1,8,5,24,90.3,3.4,0,46893,19
1,2,E0002,4,1,1,2019-01-19,34,Male,Active,742129,1,8,8,13,78.5,3.2,1,50055,23
2,3,E0003,6,4,4,2023-01-14,58,Female,Active,921776,1,2,0,0,65.3,2.8,5,80027,14
3,4,E0004,3,3,3,2020-05-31,42,Male,Active,368277,1,5,1,32,69.3,3.7,6,967,12
4,5,E0005,5,3,1,2026-03-08,50,Male,On Leave,551005,4,1,6,6,76.5,3.1,4,38246,10

In [10]:
departments

   DeptID  Department  Budget_USD  Headcount_Target
0       1          HR      300000                25
1       2     Finance      500000                30
2       3          IT      900000                60
3       4       Sales      700000                55
4       5   Marketing      450000                28
5       6  Operations      650000                40

In [11]:
locations

   LocationID     City      State Region
0           1    Noida         UP  North
1           2  Lucknow         UP  North
2           3    Delhi      Delhi  North
3           4   Jaipur  Rajasthan   West

In [12]:
jobs

   JobID    JobTitle Grade  BaseSalaryBand
0      1     Analyst    G4          600000
1      2     Manager    G7         1200000
2      3   Executive    G3          450000
3      4    Engineer    G5          900000
4      5  Specialist    G5          800000
5      6   Associate    G2          350000
6      7        Lead    G6         1100000
7      8      Intern    G1          180000

In [13]:
attendance.head()

   EmployeeID  DaysPresent  LeavesTaken  WFHDays  LateMarks
0           1          205           10        7          6
1           2          252            7       15          8
2           3          223            8       15         11
3           4          242           14        5         11
4           5          225            5        4         11

In [14]:
attrition.head()

   EmployeeID      ExitReason  NoticePeriodDays
0          14      Relocation                59
1          15      Relocation                15
2          17             Pay                20
3          35      Relocation                90
4          37  Higher Studies                 5

In [15]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   EmployeeID           230 non-null    int64
 1   EmpCode              230 non-null    str
 2   DeptID               230 non-null    int64
 3   LocationID           230 non-null    int64
 4   JobID                230 non-null    int64
 5   HireDate             230 non-null    datetime64[us]
 6   Age                  230 non-null    int64
 7   Gender               230 non-null    str
 8   EmploymentStatus     230 non-null    str
 9   Salary               230 non-null    int64
 10  PerformanceRating    230 non-null    int64
 11  TrainingHours        230 non-null    int64
 12  AbsenteeismDays      230 non-null    int64
 13  OvertimeHours        230 non-null    int64
 14  EngagementScore      230 non-null    float64
 15  SatisfactionScore    230 non-null    float64
 16  YearsSincePromotion  230 non-null    int64
 17  Bonus                230 non-null    int64
 18  ManagerID            230 non-null    int64
dtypes: datetime64[us](1), float64(2), int64(13), str(3)
memory usage: 34.3 KB

In [16]:
employees.shape

(230, 19)

Data Integration (Merging all sheets)

In [17]:
df = employees.merge(departments,on='DeptID',how='left')

In [18]:
df = df.merge(locations,on="LocationID",how="left")

In [19]:
df = df.merge(jobs,on='JobID',how='left')
df = df.merge(attendance,on='EmployeeID',how='left')
df = df.merge(attrition,on='EmployeeID',how='left')

In [20]:
df.head()

,EmployeeID,EmpCode,DeptID,LocationID,JobID,HireDate,Age,Gender,EmploymentStatus,Salary,...,Region,JobTitle,Grade,BaseSalaryBand,DaysPresent,LeavesTaken,WFHDays,LateMarks,ExitReason,NoticePeriodDays
0,1,E0001,6,1,1,2021-01-31,36,Male,Active,644704,...,North,Analyst,G4,600000,205,10,7,6,NaN,NaN
1,2,E0002,4,1,1,2019-01-19,34,Male,Active,742129,...,North,Analyst,G4,600000,252,7,15,8,NaN,NaN
2,3,E0003,6,4,4,2023-01-14,58,Female,Active,921776,...,West,Engineer,G5,900000,223,8,15,11,NaN,NaN
3,4,E0004,3,3,3,2020-05-31,42,Male,Active,368277,...,North,Executive,G3,450000,242,14,5,11,NaN,NaN
4,5,E0005,5,3,1,2026-03-08,50,Male,On Leave,551005,...,North,Analyst,G4,600000,225,5,4,11,NaN,NaN

In [21]:
df['ExitReason'].notnull()

0      False
1      False
2      False
3      False
4      False
       ...
225    False
226    False
227    False
228    False
229    False
Name: ExitReason, Length: 230, dtype: bool

In [22]:
df['Is_Attrited'] = df['ExitReason'].notnull()

In [23]:
df.head()

,EmployeeID,EmpCode,DeptID,LocationID,JobID,HireDate,Age,Gender,EmploymentStatus,Salary,...,JobTitle,Grade,BaseSalaryBand,DaysPresent,LeavesTaken,WFHDays,LateMarks,ExitReason,NoticePeriodDays,Is_Attrited
0,1,E0001,6,1,1,2021-01-31,36,Male,Active,644704,...,Analyst,G4,600000,205,10,7,6,NaN,NaN,False
1,2,E0002,4,1,1,2019-01-19,34,Male,Active,742129,...,Analyst,G4,600000,252,7,15,8,NaN,NaN,False
2,3,E0003,6,4,4,2023-01-14,58,Female,Active,921776,...,Engineer,G5,900000,223,8,15,11,NaN,NaN,False
3,4,E0004,3,3,3,2020-05-31,42,Male,Active,368277,...,Executive,G3,450000,242,14,5,11,NaN,NaN,False
4,5,E0005,5,3,1,2026-03-08,50,Male,On Leave,551005,...,Analyst,G4,600000,225,5,4,11,NaN,NaN,False

In [45]:
print(df.columns)

Index(['EmployeeID', 'EmpCode', 'DeptID', 'LocationID', 'JobID', 'HireDate',
       'Age', 'Gender', 'EmploymentStatus', 'Salary', 'PerformanceRating',
       'TrainingHours', 'AbsenteeismDays', 'OvertimeHours', 'EngagementScore',
       'SatisfactionScore', 'YearsSincePromotion', 'Bonus', 'ManagerID',
       'Department', 'Budget_USD', 'Headcount_Target', 'City', 'State',
       'Region', 'JobTitle', 'Grade', 'BaseSalaryBand', 'DaysPresent',
       'LeavesTaken', 'WFHDays', 'LateMarks', 'ExitReason', 'NoticePeriodDays',
       'Is_Attrited', 'Attrition_numeric'],
      dtype='str')

In [25]:
df['Attrition_numeric'] = df['Is_Attrited'].astype(int)

Key HR Metrics

In [26]:
metrics = {
    'Total Employees':len(df),
    'Average Salary':df['Salary'].mean(),
    'Attrition Rate %': (df['Is_Attrited'].sum()/len(df))*100,
    "Avg engagement Score":df['EngagementScore'].mean(),
    'Avg Satisfaction Score':df['SatisfactionScore'].mean(),
    'Total Bonus pool':df['Bonus'].sum(),
    'Avg Training Hours':df['TrainingHours'].mean(),
    'Avg Age':df['Age'].mean(),
    'Departments':df['Department'].nunique(),
    'Avg year since Promotion':df['YearsSincePromotion'].mean()
}

In [27]:
for k,v in metrics.items():
    print(f"{k}: {v:,.2f}")

Total Employees: 230.00
Average Salary: 718,704.14
Attrition Rate %: 18.26
Avg engagement Score: 72.65
Avg Satisfaction Score: 3.56
Total Bonus pool: 13,899,026.00
Avg Training Hours: 4.27
Avg Age: 39.98
Departments: 6.00
Avg year since Promotion: 2.94

<h2>Insights</h2>

In [28]:
df.groupby('Department')['Salary'].sum()

Department
Finance       19860033
HR            20105956
IT            42406580
Marketing     28222957
Operations    23453282
Sales         31253145
Name: Salary, dtype: int64

In [29]:
df.groupby('Department')['Salary'].mean().idxmax()

'IT'

In [30]:
df.groupby('Department')['Salary'].mean().idxmin()

'Finance'

Gender Distribution

In [31]:
(df['Gender']=='Male').mean()*100

np.float64(53.91304347826087)

In [32]:
(df['Gender']=='Female').mean()*100

np.float64(46.08695652173913)

Grouping with Attrition rate

In [33]:
df.groupby('Department')['Attrition_numeric'].mean()*100

Department
Finance       20.000000
HR             7.142857
IT            18.181818
Marketing     23.076923
Operations    17.647059
Sales         20.454545
Name: Attrition_numeric, dtype: float64

In [34]:
df.groupby('Department')['Attrition_numeric'].mean().idxmax()

'Marketing'

Most commong exit reason

In [35]:
df['ExitReason'].value_counts()

ExitReason
Manager           11
Career Growth     10
Relocation         8
Pay                8
Higher Studies     5
Name: count, dtype: int64

In [36]:
df['City'].value_counts()

City
Delhi      66
Noida      63
Lucknow    52
Jaipur     49
Name: count, dtype: int64

In [37]:
df['SatisfactionScore'].corr(df['OvertimeHours'])

np.float64(0.10132264223873845)

In [41]:
print(df[df['Department']=='Sales']['Salary'].sum())

31253145

In [42]:
df.pivot_table(values='Salary',index='Department',columns='City',aggfunc='sum')

City           Delhi   Jaipur   Lucknow     Noida
Department
Finance      6052682  2215211   6215031   5377109
HR           3499500  4610902   3078858   8916696
IT          13605070  5565492  10212413  13023605
Marketing    5578212  6423915   9734437   6486393
Operations   7925671  7265284   2080388   6181939
Sales        8724296  8256164   7747602   6525083

In [51]:
(df['PerformanceRating']>=4).mean()*100

np.float64(42.608695652173914)

Age distribution