<h1>Univariate Imputation- Categorical Data</h1>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data = {
    'City':["Delhi","Noida","Meerut","Noida",np.nan,np.nan,"Delhi",'Noida'],
    'Membership':['Gold','Silver',np.nan,'Silver',np.nan,np.nan,'Silver',np.nan]
}

In [2]:
df = pd.DataFrame(data)

Mode Imputation

In [7]:
from sklearn.impute import SimpleImputer

imputer_mode = SimpleImputer(strategy='most_frequent')
df[['City_Mode','Membership_mode']] = imputer_mode.fit_transform(df[['City','Membership']])

In [8]:
df

     City Membership City_Mode Membership_mode
0   Delhi       Gold     Delhi            Gold
1   Noida     Silver     Noida          Silver
2  Meerut        NaN    Meerut          Silver
3   Noida     Silver     Noida          Silver
4     NaN        NaN     Noida          Silver
5     NaN        NaN     Noida          Silver
6   Delhi     Silver     Delhi          Silver
7   Noida        NaN     Noida          Silver

Constant Value Imputation ("Missing","Unknown","Not given")

In [9]:
df['Membership_constant'] = df['Membership'].fillna("Missing")

In [10]:
df

     City Membership City_Mode Membership_mode Membership_constant
0   Delhi       Gold     Delhi            Gold                Gold
1   Noida     Silver     Noida          Silver              Silver
2  Meerut        NaN    Meerut          Silver             Missing
3   Noida     Silver     Noida          Silver              Silver
4     NaN        NaN     Noida          Silver             Missing
5     NaN        NaN     Noida          Silver             Missing
6   Delhi     Silver     Delhi          Silver              Silver
7   Noida        NaN     Noida          Silver             Missing

In [22]:
df['Membership'].bfill()

0      Gold
1    Silver
2    Silver
3    Silver
4    Silver
5    Silver
6    Silver
7       NaN
Name: Membership, dtype: str

<h1>Multivariate Imputation</h1>

- KNN (K Nearest neighbors)
- Iterative

In [23]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

In [24]:
data = {
    'Experience':[1,2,3,10,11,12,20,21,np.nan],
    'Salary':[45000,50000,np.nan,110000,120000,125000,200000,np.nan,210000],
    'Age':[22,24,23,35,np.nan,38,50,51,52]
}

df = pd.DataFrame(data)

In [25]:
df

   Experience    Salary   Age
0         1.0   45000.0  22.0
1         2.0   50000.0  24.0
2         3.0       NaN  23.0
3        10.0  110000.0  35.0
4        11.0  120000.0   NaN
5        12.0  125000.0  38.0
6        20.0  200000.0  50.0
7        21.0       NaN  51.0
8         NaN  210000.0  52.0

In [26]:
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

df = pd.DataFrame(df_scaled,columns=df.columns)
df

   Experience    Salary       Age
0   -1.242118 -1.300386 -1.222266
1   -1.104105 -1.216875 -1.057928
2   -0.966092       NaN -1.140097
3    0.000000 -0.214743 -0.154067
4    0.138013 -0.047721       NaN
5    0.276026  0.035790  0.092440
6    1.380131  1.288456  1.078470
7    1.518144       NaN  1.160639
8         NaN  1.455478  1.242808

In [30]:
imputer = KNNImputer(n_neighbors=3)

df_imputed = imputer.fit_transform(df)
df_imputed

array([[-1.24211801, -1.30038642, -1.22226591],
       [-1.10410489, -1.21687536, -1.05792764],
       [-0.96609178, -0.91066817, -1.14009677],
       [ 0.        , -0.21474271, -0.15406713],
       [ 0.13801311, -0.0477206 , -0.40057454],
       [ 0.27602622,  0.03579045,  0.09244028],
       [ 1.38013112,  1.28845627,  1.07846992],
       [ 1.51814423,  0.92657503,  1.16063906],
       [ 1.05810052,  1.45547838,  1.2428082 ]])

In [29]:
imputer = KNNImputer(n_neighbors=3)

df_imputed = imputer.fit_transform(df)
df_inverse = scaler.inverse_transform(df_imputed)
df_final = pd.DataFrame(df_inverse,columns=df.columns)
df_final

   Experience         Salary   Age
0    1.000000   45000.000000  22.0
1    2.000000   50000.000000  24.0
2    3.000000   68333.333333  23.0
3   10.000000  110000.000000  35.0
4   11.000000  120000.000000  32.0
5   12.000000  125000.000000  38.0
6   20.000000  200000.000000  50.0
7   21.000000  178333.333333  51.0
8   17.666667  210000.000000  52.0

<h1>Iterative Imputer</h1>

In [31]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler

In [33]:
np.random.seed(42)

age = np.random.randint(20,60,100)
income = (age*2000) + np.random.normal(0,5000,100)

df = pd.DataFrame({'Age':age,'Income':income})
df.head(10)

   Age         Income
0   58  115111.339394
1   48   93948.083457
2   34   73898.581724
3   27   49508.960303
4   40   84173.977096
5   58  117482.806922
6   38   70810.850617
7   42   83620.981275
8   30   64864.817669
9   30   63977.977319

In [34]:
df.iloc[1:10,0] = np.nan
df.iloc[50:60,1] = np.nan

In [39]:
df.isnull().sum()

Age        9
Income    10
dtype: int64

In [40]:
scaler = StandardScaler()
df_s = scaler.fit_transform(df)
df_scaled = pd.DataFrame(df_s,columns=df.columns)
df_scaled

         Age    Income
0   1.641162  1.547841
1        NaN  0.659227
2        NaN -0.182623
3        NaN -1.206708
4        NaN  0.248826
..       ...       ...
95 -0.924916 -0.684174
96 -1.010452 -0.745337
97 -0.668308 -0.864278
98  1.213482  1.294939
99  1.127946  1.336807

[100 rows x 2 columns]

In [41]:
it_imputer = IterativeImputer(max_iter=10,random_state=42)
df_imputed_scaled = it_imputer.fit_transform(df_scaled)

df_inverse = scaler.inverse_transform(df_imputed_scaled)
df_final = pd.DataFrame(df_inverse,columns=df.columns)

In [44]:
df_final.head(10)

         Age         Income
0  58.000000  115111.339394
1  46.009204   93948.083457
2  36.792443   73898.581724
3  25.580528   49508.960303
4  41.516045   84173.977096
5  56.828123  117482.806922
6  35.373012   70810.850617
7  41.261833   83620.981275
8  32.639619   64864.817669
9  32.231939   63977.977319