<h1>Scaling</h1>

Transforming features so they are on similar scale

In [11]:
import pandas as pd
import numpy as np

data = {
    'age':np.random.randint(20,55,100),
    'salary':np.random.randint(30000,100000,100)
}

df = pd.DataFrame(data)
df.head(10)

   age  salary
0   44   71212
1   44   58356
2   26   55905
3   48   82931
4   26   82600
5   41   31408
6   45   52002
7   53   68267
8   40   91344
9   32   96555

<h2>Standard Scaler</h2>

In [2]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[['age_scaled','salary_scaled']] = scaler.fit_transform(df[['age','salary']])

In [10]:
df.head(10)

,age,salary,age_scaled,salary_scaled,age_scaled_manual,actual_age_manual,age_scaled_inverse,salary_scaled_inverse
0,34,42113,-0.399211,-1.067888,-0.397210,34.0,34.0,42113.0
1,45,42451,0.784434,-1.050403,0.780502,45.0,45.0,42451.0
2,32,89387,-0.614419,1.377632,-0.611340,32.0,32.0,89387.0
3,20,35876,-1.905669,-1.390533,-1.896116,20.0,20.0,35876.0
4,24,69383,-1.475252,0.342809,-1.467858,24.0,24.0,69383.0
5,51,35674,1.430059,-1.400983,1.422890,51.0,51.0,35674.0
6,29,91505,-0.937232,1.487197,-0.932534,29.0,29.0,91505.0
7,39,73652,0.138809,0.563648,0.138114,39.0,39.0,73652.0
8,33,61874,-0.506815,-0.045637,-0.504275,33.0,33.0,61874.0
9,29,88954,-0.937232,1.355232,-0.932534,29.0,29.0,88954.0

In [4]:
df['age_scaled_manual'] = (df['age']-df['age'].mean())/df['age'].std()

In [7]:
df['actual_age_manual'] = df['age_scaled_manual']*df['age'].std() + df['age'].mean()

In [9]:
df[['age_scaled_inverse','salary_scaled_inverse']] = scaler.inverse_transform(df[['age_scaled','salary_scaled']] )

<h2>Min-Max Scaler</h2>

In [13]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['age_scaled','salary_scaled']] = scaler.fit_transform(df[['age','salary']])

In [21]:
df.head(10)

,age,salary,age_scaled,salary_scaled,age_scaled_manual,age_inverse,salary_inverse
0,44,71212,0.705882,0.585913,0.705882,44.0,71212.0
1,44,58356,0.705882,0.396673,0.705882,44.0,58356.0
2,26,55905,0.176471,0.360595,0.176471,26.0,55905.0
3,48,82931,0.823529,0.758416,0.823529,48.0,82931.0
4,26,82600,0.176471,0.753544,0.176471,26.0,82600.0
5,41,31408,0.617647,0.000000,0.617647,41.0,31408.0
6,45,52002,0.735294,0.303143,0.735294,45.0,52002.0
7,53,68267,0.970588,0.542563,0.970588,53.0,68267.0
8,40,91344,0.588235,0.882255,0.588235,40.0,91344.0
9,32,96555,0.352941,0.958961,0.352941,32.0,96555.0

In [15]:
age_min = df['age'].min()
age_max = df['age'].max()

In [16]:
df['age_scaled_manual'] = (df['age'] - age_min)/(age_max - age_min)

In [20]:
df[['age_inverse','salary_inverse']] = scaler.inverse_transform(df[['age_scaled','salary_scaled']])