In [3]:
import numpy as np
import pandas as pd


np.random.seed(42)

n = 100

df = pd.DataFrame(
    {
        "Age":np.random.randint(18,55,n),
        "Salary":np.random.randint(30000,100000,n),
        "experience":np.random.randint(1,30,n),
        "hours_worked":np.random.randint(4,12,n)
    }
)

df.head(10)

   Age  Salary  experience  hours_worked
0   46   38110          16             9
1   32   57266          12             8
2   25   82992           5            10
3   38   36910           5             6
4   36   30206          27             7
5   40   53419          23             4
6   28   80636           9             7
7   28   80015           9            10
8   41   84268           3             8
9   53   48141          19             8

In [22]:
df.head(20)

,Age,Salary,experience,hours_worked,Salary_per_exp,age_exp_interaction,Age_group,salary_hike,Work_hr_group,ch
0,46,38110,16,9,2381.875000,736,senior,41921.0,middle,B
1,32,57266,12,8,4772.166667,384,middle,62992.6,middle,B
2,25,82992,5,10,16598.400000,125,young,82992.0,middle,B
3,38,36910,5,6,7382.000000,190,middle,36910.0,least,A
4,36,30206,27,7,1118.740741,972,middle,33226.6,least,A
5,40,53419,23,4,2322.565217,920,middle,58760.9,least,A
6,28,80636,9,7,8959.555556,252,young,80636.0,least,A
7,28,80015,9,10,8890.555556,252,young,80015.0,middle,B
8,41,84268,3,8,28089.333333,123,middle,84268.0,middle,B
9,53,48141,19,8,2533.736842,1007,senior,52955.1,middle,B
10,41,86044,16,11,5377.750000,656,middle,94648.4,much,C
11,20,97214,16,10,6075.875000,320,young,106935.4,middle,B
12,39,63827,3,4,21275.666667,117,middle,63827.0,least,A
13,19,85820,20,11,4291.000000,380,young,94402.0,much,C
14,41,92623,24,6,3859.291667,984,middle,101885.3,least,A
15,47,52299,22,11,2377.227273,1034,senior,57528.9,much,C
16,19,73585,24,5,3066.041667,456,young,80943.5,least,A
17,38,94044,1,4,94044.000000,38,middle,94044.0,least,A
18,50,72557,24,5,3023.208333,1200,senior,79812.7,least,A
19,29,79080,20,10,3954.000000,580,middle,86988.0,middle,B

In [4]:
df['Salary_per_exp'] = df['Salary']/df['experience']

In [6]:
df['age_exp_interaction'] = df['Age']*df['experience']

In [7]:
df['Age_group'] = pd.cut(
    df['Age'],
    bins=[18,28,42,60],
    labels = ['young','middle','senior']
)

In [9]:
df['salary_hike'] = np.where(df['experience']>10,df['Salary']+df['Salary']*0.1,df['Salary'])

In [15]:
df['Work_hr_group'] = pd.cut(
    df['hours_worked'],
    bins=[3,7,10,12],
    labels = ['least','middle','much']
)

In [21]:
conditions = [df['hours_worked']<=7,df['hours_worked']<=10,df['hours_worked']<=12]

choices = ["A","B","C"]

df['ch'] = np.select(conditions,choices)